# Generated by Django 3.2.7 on 2021-10-20 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_loc', models.URLField()),
                ('plant_pic', models.ImageField(default='default.jpg', upload_to='plant_pics')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
