# Generated by Django 3.2.7 on 2021-11-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PariveshApp', '0002_auto_20211103_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantation',
            name='plant_pic',
            field=models.ImageField(default='default_plant_pic.jpg', upload_to='plant_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_plant_pic.png', upload_to='profile_pics'),
        ),
    ]
